export enum NestValueOptionEnum {
  CRUD_MYSQL_LOGIN_INTERNO = "CRUD - MYSQL - LOGIN (Internal)",
  CRUD_POSTGRES_LOGIN_INTERNO = "CRUD - POSTGRES - LOGIN (Internal)",
  CRUD_MYSQL_LOGIN_KEYCLOAK = "CRUD - MYSQL - LOGIN (keycloak)",
  CRUD_MONGODB_LOGIN_INTERNO = "CRUD - MONGODB - LOGIN (Internal)",
}